LIProject/force-app/main/default/objects/Twilio_Config__c/Twilio_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains from phone number config.</description>
    <label>Twilio Config</label>
</CustomObject>

LIProject/force-app/main/default/objects/Twilio_Config__c/fields/CEO_Number__c.field-meta.xml
<CustomField>
    <fullName>CEO_Number__c</fullName>
    <description>CEO&apos;s number</description>
    <label>CEO Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LIProject/force-app/main/default/objects/Twilio_Config__c/fields/From_Number__c.field-meta.xml
<CustomField>
    <fullName>From_Number__c</fullName>
    <description>The number which the messages will be received from.</description>
    <label>From Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

LIProject/force-app/main/default/classes/TestDataFactory.cls
public with sharing class TestDataFactory {
    public static Account goldAccount(String name){
        Account gold = new Account(Name = name, Phone='+447999506611');
        insert gold;
        Opportunity o = new Opportunity(Name = name + ' opportunity', Amount=50001, AccountId = gold.Id, StageName='Closed Won', CloseDate = Date.today());
        insert o;
        return gold;
    }

    public static Account bronzeAccount(String name){
        Account gold = new Account(Name = name, Phone='+447999506611');
        insert gold;
        Opportunity o = new Opportunity(Name = name + ' opportunity', Amount=12111, AccountId = gold.Id, StageName='Closed Won', CloseDate = Date.today());
        insert o;
        return gold;
    }

    public static Twilio_Config__c twilioConfig(){
        Twilio_Config__c twilioConfig = new Twilio_Config__c(CEO_Number__c = 'testnum', From_Number__c = 'testnum');
        insert twilioConfig;
        return twilioConfig;
    }
}