LIProject/force-app/main/default/objects/Twilio_Config__c/Twilio_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains from phone number config.</description>
    <label>Twilio Config</label>
</CustomObject>

LIProject/force-app/main/default/objects/Twilio_Config__c/fields/From_Number__c.field-meta.xml
<CustomField>
    <fullName>From_Number__c</fullName>
    <description>The number which the messages will be received from.</description>
    <label>From Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

LIProject/force-app/main/default/classes/TwilioMessageSender.cls
public with sharing class TwilioMessageSender {
    public static void sendMessage(String mobileNumber, String messageBody){
        HttpRequest req = new HttpRequest();
        // get user specific config (contains the "from" phone number)
        Twilio_Config__c twilioConfig = Twilio_Config__c.getInstance();
        req.setEndpoint('callout:Twilio');
        req.setMethod('POST');
        // make sure to URL Encode the components of the request body which aren't adjacent to the To, From and Body keywords
        String toNumber = EncodingUtil.urlEncode(mobileNumber, 'UTF-8');
        String fromNumber = EncodingUtil.urlEncode(twilioConfig.From_Number__c, 'UTF-8');
        req.setBody('To=' + toNumber + '&From=' + fromNumber + '&Body=' + EncodingUtil.urlEncode(messageBody, 'UTF-8'));
        Http http = new Http();
        HTTPResponse res = http.send(req);
        // throw exception on non 201 response code
        if (res.getStatusCode() != 201){
            throw new TwilioMessageSenderException(res.getBody());
        }
    }

    public class TwilioMessageSenderException extends Exception{}
}