LIProject/force-app/main/default/objects/Twilio_Config__c/Twilio_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains from phone number config.</description>
    <label>Twilio Config</label>
</CustomObject>

LIProject/force-app/main/default/objects/Twilio_Config__c/fields/CEO_Number__c.field-meta.xml
<CustomField>
    <fullName>CEO_Number__c</fullName>
    <description>CEO&apos;s number</description>
    <label>CEO Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LIProject/force-app/main/default/classes/TwilioMessageHelper.cls
public with sharing class TwilioMessageHelper {
    @future(callout=true)
    public static void sendCEOMessages(Set<Id> opportunityIdsToSend){
        Twilio_Config__c twilioConfig = Twilio_Config__c.getInstance();
        // Method sends each message to CEO
        List<Opportunity> opportunities = [SELECT Name, Amount, CloseDate, Account.Name FROM Opportunity WHERE Id IN : opportunityIdsToSend];
        for (Opportunity opp : [SELECT Name, Amount, CloseDate, Account.Name FROM Opportunity WHERE Id IN : opportunityIdsToSend]){
            // note as this is a single currency org for now, have hard coded currency as £, if were a multi currency org would have implemented differently
            String amountFormatted = '£' + (opp.Amount).format();
            String messageBody = opp.Account.Name + ' closed on ' + opp.Name + ' for ' + amountFormatted+ ' at ' + (opp.CloseDate).format();
            TwilioMessageSender.sendMessage(twilioConfig.CEO_Number__c, messageBody); 
        } 
    }

    @AuraEnabled 
    public static void sendAccountMessage(String accId, String messageBody){
        try{
            Account acc = [SELECT Phone FROM Account WHERE Id = :accId LIMIT 1];
            TwilioMessageSender.sendMessage(acc.Phone, messageBody);
        } catch(TwilioMessageSender.TwilioMessageSenderException e){
            throw new AuraException(e.getMessage());
        }
    }
}